qiyunlab/binarena

- .gitignore
- README.md
Hi @cameronmartino, I created this empty PR. Feel free to comment on the entire codebase! Maybe it will be helpful that we meet next time to go over the codebase together.
> started code review

- static/js/silhouette.js
- static/js/util.js
- tests/runner.html
- tests/silhouette.test.js
- tests/util.test.js
silhouette score functions added, including functions of:
euclidean distance - calculate the euclidean distance between 2 points
pairwise distance  - calculate the distance matrix between each 2 points
bin count - output the occurrence of each element in given input data array
silhouette score - compute the silhouette score according to [https://en.wikipedia.org/wiki/Silhouette_(clustering)](url)
> silhouette score functions added

- static/js/ari.js
- static/js/silhouette.js
- tests/ari.test.js
- tests/runner.html
result same to [sklearn.metrics.adjusted_rand_score](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.adjusted_rand_score.html)
> functions of adjusted rand index added

- static/js/gmm.js
- tests/gmm.test.js
- tests/runner.html
> GMM functions added

- static/js/operation.js
- static/js/rule.js
- static/js/util.js
Hello @AbhinavChede I wrote this pull request to patch the issues we have discussed and a few other minor issues. I would encourage that you read the code and try to understand the logic. Please let me know if you spot anything wrong. Thank you!
> Multiple adjustments to the assembly parsing function

- static/js/operation.js
This bug prevented correct listing of categorical columns.
> Fixed category list bug

- BinaRena.html
- static/css/style.css
- static/js/algorithm.js
- static/js/gmm.js
- static/js/interface.js
- static/js/numeric.js
Modified the mechanism of the floating message window (i.e., "toast"). If the duration time is set to be zero, the window will stay visible with a close button, until the user closes it. This is useful when displaying important messages, such as the calculation results of silhouette coefficient. Here is the screenshot:
> Made toast visible until the user closes it.

- BinaRena.html
- static/css/style.css
- static/js/algorithm.js
- static/js/control.js
- static/js/interface.js
- static/js/numeric.js
- static/js/operation.js
- tests/numeric.test.js
Added GUI components to enable caculation of the adjusted Rand index. The algorithm was originally implemented by @nujinuji .
> Integrated adjusted Rand index calculation

- BinaRena.html
- static/css/style.css
- static/js/control.js
- static/js/interface.js
- static/js/main.js
- static/js/numeric.js
- static/js/operation.js
- static/js/render.js
- static/js/util.js
- tests/numeric.test.js
Added a mini plot below the display panel. It shows a histogram of the designated variable of the selected contigs.
> Add a mini plot of variable distribution

- BinaRena.html
- static/css/style.css
- static/js/algorithm.js
- static/js/control.js
- static/js/interface.js
- static/js/main.js
- static/js/numeric.js
- static/js/render.js
- static/js/resource.js
The mini plot now can highlight bars, do log transformation, increase / decrease resolution, and let the user use mouse to drag a range of bars to refine the selected contigs. @AbhinavChede
> Improved mini plot

- BinaRena.html
- README.md
- static/css/style.css
- static/css/theme.css
- static/js/control.js
- static/js/interface.js
- static/js/main.js
- static/js/numeric.js
- static/js/operation.js
- static/js/render.js
- static/js/resource.js
- static/js/rule.js
- static/js/util.js
> Improved binning and selection functionality

- static/js/input.js
Hi @qiyunzhu ,
I have made the regexes simpler for the parseContigTitle method. Please let me know if I need to fix anything else about the regexes.
Thank you
Abhinav Chede
> [WIP] Simpler Regex

- BinaRena.html
- static/css/style.css
- static/js/algorithm.js
- static/js/interface.js
- static/js/render.js
Now the program can generate an SVG image file. It is basically a separate rendering engine. It is useful for further manipulation and publication of the graphs. Partially addressed #35 @AbhinavChede
> Added SVG export

- BinaRena.html
- static/js/display.js
- static/js/main.js
- static/js/render.js
- static/js/select.js
Addressed #59 . Now the user can select contigs, press "F" such that only selected ones are displayed. The user can then work on them without distraction. When done, they press "F" again to display all  other contigs.
> Added focus mode

- BinaRena.html
- scripts/README.md
- scripts/checkm_marker_list.py
- scripts/checkm_markers_map.py
- static/css/style.css
- static/js/binning.js
- static/js/calculate.js
- static/js/datable.js
- static/js/display.js
- static/js/input.js
- static/js/interface.js
- static/js/main.js
- static/js/miniplot.js
- static/js/rule.js
- static/js/select.js
- static/js/util.js
This is a major upgrade containing multiple improvements, including:
- Can calculate CheckM-like completeness/contamination based on the membership of a user-defined feature group (such as a CheckM or GTDB-tk marker gene set; a KEGG metabolic pathway, etc.)
- Have a new data import window. Can handle table (3+ columns), map (2 columns) and membership list (1 column).
- Let user 1) Select data types of columns when importing a data table. 2) Append new data columns to an existing dataset. 3) Delete existing data columns.
- Better handling of two special columns: "length" and "coverage".
- Improved UI and fixed several bugs.
Demo of real-time completeness / contamination calculation:
> Multiple improvements

- scripts/checkm_marker_list.py
Now it reports the correct list of marker genes.
> Fixed CheckM marker gene list

- static/js/main.js
- static/js/select.js
This fixed the issue of inconsistency in scatter plot position and masked contig count when unfocusing contigs.
> Fixed focus issue

- static/js/main.js
- static/js/render.js
Based on @AbhinavChede 's #68. Resolved some issues.
> Updated touchpad support

- static/js/render.js
Hi @qiyunzhu ,
I have wrote the functionality for touch screen support in BinaRena. It does perform normal touch screen options like translating and zooming. However, currently, it cannot do both at the same time. Additionally, to make the code cleaner, I could use functions but then I would have to create global variables in the `render.js` file. Let me know what you think.
> [WIP] Touch Screen Support

- static/js/interface.js
- static/js/render.js
- static/js/rule.js
- tests/input.test.js
- tests/rule.test.js
> Attempted to improve rendering

- static/js/algorithm.js
- static/js/binning.js
- static/js/datable.js
- static/js/numeric.js
- static/js/render.js
- static/js/select.js
- static/js/util.js
Previous implementation was slow when there are many bins (hundreds). Now improved.
> Fixed large bin table sorting issue

- static/css/style.css
- static/js/calculate.js
Removed contigs that are unbinned in either or both plan prior to calculating ARI.
> Improved adjusted Rand index

- BinaRena.html
- README.md
- static/js/algorithm.js
- static/js/binning.js
- static/js/display.js
- static/js/gmm.js
- static/js/input.js
- static/js/interface.js
- static/js/main.js
- static/js/miniplot.js
- static/js/numeric.js
- static/js/plot.js
- static/js/render.js
- static/js/select.js
- static/js/svg.js
- static/js/worker.js
Now it can cache images around viewport to accelerate future rendering.
> Improved rendering engine

- static/js/plot.js
- static/js/render.js
- static/js/worker.js
> Tweaked rendering engine

- README.md
As the paper has been published.
> updated publication
